sudo: required
services:
  - docker

before_install:
  - docker build -t paulhe001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulhe001/docker-react npm run test -- --coverage
